version: '3'

services:
  nginx:
    image: nginx:1.10.3
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/default.conf
      - ./docker/nginx/nginx.log:/var/log/nginx/error.log
    environment:
      project_name: ${APP_NAME}
    working_dir:
      /var/www
    command: /bin/bash -c "envsubst '$$project_name' < /default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - php


  php:
    build:
      context: ./docker/php/
      dockerfile: php.Dockerfile
      args:
        USER_ID: ${USER_ID}
    volumes:
      - ./:/var/www
      - ./.env:/.env

    environment:
      APP_NAME: ${APP_NAME}
    ports:
      - 9000:9000
    depends_on:
      - database
    working_dir:
      /var/www
    user: '1000'

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - database
    ports:
     - 8080:80
    volumes:
     - /sessions




